/*
 * Copyright (C) 2017 Felipe Henrique Ferraresi
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/**
 *
 * @author Felipe Henrique Ferraresi
 */
package pythonferraresiconverter;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author felipe
 */
public class SelectFile extends javax.swing.JFrame {

    /**
     * Creates new form SelectFile
     */
    private static String arquivo = "";
    private static final String python = System.getenv("APPDATA") + "Local\\Programs\\Python\\Python36-32\\python.exe";
    private static String comando;

    public SelectFile() {
        initComponents();

        try {
            int returnVal = jFileChooser1.showOpenDialog(null);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                arquivo = "";
                File file = jFileChooser1.getSelectedFile();
                /*  try { 
                 System.out.print(file.getAbsoluteFile());
                 } catch (IOException ex) {
                 System.out.println("problem accessing file" + file.getAbsolutePath());
                 }*/
                arquivo = file.getAbsolutePath().replaceAll(".ui", "");
                System.out.println(arquivo + "\n\n");

                Process exec;
                try {
                    if (arquivo.equals("") || arquivo == "" || arquivo == null) {
                        JOptionPane.showMessageDialog(null, "Occorreu um erro no momento de executar a conversão [1]");
                        return;
                    }

                    comando = python.replaceAll("Roaming", "") + " -m PyQt5.uic.pyuic " + arquivo + ".ui -o " + arquivo + ".py -x";
                    System.out.print(comando);
                    exec = Runtime.getRuntime().exec(comando);
                    if (exec.waitFor() == 0) {
                        new SucessMensage().setVisible(true);
                    } else {
                        System.out.println("ERRO");
                    }
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Occorreu um erro no momento de abrir o arquivo");
                    e.printStackTrace();
                } catch (InterruptedException e) {
                    JOptionPane.showMessageDialog(null, "Occorreu um erro no momento de executar a conversão [2]");
                    e.printStackTrace();
                } catch (NullPointerException e) {
                    JOptionPane.showMessageDialog(null, "Occorreu um erro no momento de executar a conversão [3]");
                    e.printStackTrace();
                }
            } else {
                System.out.println("Esse troxa não quis fazer nada com o aquivo.");
            }
            this.dispose();
        } catch (Exception e) {

        } finally {
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        jFileChooser1.setDialogTitle("");
        jFileChooser1.setFileFilter(new MyCustomFilter());
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed

    }//GEN-LAST:event_jFileChooser1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
